python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model Mixtral-8x7B-Instruct-v0.1 -p newseye_guidelines_norole
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model Mixtral-8x7B-Instruct-v0.1 -p newseye_guidelines_role
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model Mixtral-8x7B-Instruct-v0.1 -p newseye_noguidelines_norole
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model Mixtral-8x7B-Instruct-v0.1 -p newseye_noguidelines_role
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model zephyr-7b-beta -p newseye_guidelines_norole
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model zephyr-7b-beta -p newseye_guidelines_role
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model zephyr-7b-beta -p newseye_noguidelines_norole
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model zephyr-7b-beta -p newseye_noguidelines_role
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model Meta-Llama-3-70B-Instruct -p newseye_guidelines_norole
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model Meta-Llama-3-70B-Instruct -p newseye_guidelines_role
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model Meta-Llama-3-70B-Instruct -p newseye_noguidelines_norole
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model Meta-Llama-3-70B-Instruct -p newseye_noguidelines_role
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model Llama-2-70b-chat-hf -p newseye_guidelines_norole
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model Llama-2-70b-chat-hf -p newseye_guidelines_role
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model Llama-2-70b-chat-hf -p newseye_noguidelines_norole
python extract_entities.py -i datasets/Newseye/de/HIPE-2022-v2.1-newseye-test-de.tsv --model Llama-2-70b-chat-hf -p newseye_noguidelines_role
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model Mixtral-8x7B-Instruct-v0.1 -p newseye_guidelines_norole
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model Mixtral-8x7B-Instruct-v0.1 -p newseye_guidelines_role
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model Mixtral-8x7B-Instruct-v0.1 -p newseye_noguidelines_norole
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model Mixtral-8x7B-Instruct-v0.1 -p newseye_noguidelines_role
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model zephyr-7b-beta -p newseye_guidelines_norole
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model zephyr-7b-beta -p newseye_guidelines_role
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model zephyr-7b-beta -p newseye_noguidelines_norole
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model zephyr-7b-beta -p newseye_noguidelines_role
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model Meta-Llama-3-70B-Instruct -p newseye_guidelines_norole
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model Meta-Llama-3-70B-Instruct -p newseye_guidelines_role
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model Meta-Llama-3-70B-Instruct -p newseye_noguidelines_norole
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model Meta-Llama-3-70B-Instruct -p newseye_noguidelines_role
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model Llama-2-70b-chat-hf -p newseye_guidelines_norole
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model Llama-2-70b-chat-hf -p newseye_guidelines_role
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model Llama-2-70b-chat-hf -p newseye_noguidelines_norole
python extract_entities.py -i datasets/Newseye/fr/NewsEye-GT-NER_EL_StD-v1-test-fr.tsv --model Llama-2-70b-chat-hf -p newseye_noguidelines_role
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model Mixtral-8x7B-Instruct-v0.1 -p ajmc_guidelines_norole
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model Mixtral-8x7B-Instruct-v0.1 -p ajmc_guidelines_role
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model Mixtral-8x7B-Instruct-v0.1 -p ajmc_noguidelines_norole
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model Mixtral-8x7B-Instruct-v0.1 -p ajmc_noguidelines_role
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model zephyr-7b-beta -p ajmc_guidelines_norole
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model zephyr-7b-beta -p ajmc_guidelines_role
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model zephyr-7b-beta -p ajmc_noguidelines_norole
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model zephyr-7b-beta -p ajmc_noguidelines_role
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model Meta-Llama-3-70B-Instruct -p ajmc_guidelines_norole
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model Meta-Llama-3-70B-Instruct -p ajmc_guidelines_role
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model Meta-Llama-3-70B-Instruct -p ajmc_noguidelines_norole
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model Meta-Llama-3-70B-Instruct -p ajmc_noguidelines_role
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model Llama-2-70b-chat-hf -p ajmc_guidelines_norole
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model Llama-2-70b-chat-hf -p ajmc_guidelines_role
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model Llama-2-70b-chat-hf -p ajmc_noguidelines_norole
python extract_entities.py -i datasets/AJMC/de/HIPE-2022-v2.1-ajmc-test-de.tsv --model Llama-2-70b-chat-hf -p ajmc_noguidelines_role
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model Mixtral-8x7B-Instruct-v0.1 -p ajmc_guidelines_norole
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model Mixtral-8x7B-Instruct-v0.1 -p ajmc_guidelines_role
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model Mixtral-8x7B-Instruct-v0.1 -p ajmc_noguidelines_norole
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model Mixtral-8x7B-Instruct-v0.1 -p ajmc_noguidelines_role
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model zephyr-7b-beta -p ajmc_guidelines_norole
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model zephyr-7b-beta -p ajmc_guidelines_role
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model zephyr-7b-beta -p ajmc_noguidelines_norole
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model zephyr-7b-beta -p ajmc_noguidelines_role
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model Meta-Llama-3-70B-Instruct -p ajmc_guidelines_norole
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model Meta-Llama-3-70B-Instruct -p ajmc_guidelines_role
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model Meta-Llama-3-70B-Instruct -p ajmc_noguidelines_norole
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model Meta-Llama-3-70B-Instruct -p ajmc_noguidelines_role
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model Llama-2-70b-chat-hf -p ajmc_guidelines_norole
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model Llama-2-70b-chat-hf -p ajmc_guidelines_role
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model Llama-2-70b-chat-hf -p ajmc_noguidelines_norole
python extract_entities.py -i datasets/AJMC/en/HIPE-2022-v2.1-ajmc-test-en.tsv --model Llama-2-70b-chat-hf -p ajmc_noguidelines_role
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model Mixtral-8x7B-Instruct-v0.1 -p ajmc_guidelines_norole
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model Mixtral-8x7B-Instruct-v0.1 -p ajmc_guidelines_role
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model Mixtral-8x7B-Instruct-v0.1 -p ajmc_noguidelines_norole
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model Mixtral-8x7B-Instruct-v0.1 -p ajmc_noguidelines_role
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model zephyr-7b-beta -p ajmc_guidelines_norole
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model zephyr-7b-beta -p ajmc_guidelines_role
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model zephyr-7b-beta -p ajmc_noguidelines_norole
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model zephyr-7b-beta -p ajmc_noguidelines_role
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model Meta-Llama-3-70B-Instruct -p ajmc_guidelines_norole
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model Meta-Llama-3-70B-Instruct -p ajmc_guidelines_role
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model Meta-Llama-3-70B-Instruct -p ajmc_noguidelines_norole
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model Meta-Llama-3-70B-Instruct -p ajmc_noguidelines_role
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model Llama-2-70b-chat-hf -p ajmc_guidelines_norole
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model Llama-2-70b-chat-hf -p ajmc_guidelines_role
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model Llama-2-70b-chat-hf -p ajmc_noguidelines_norole
python extract_entities.py -i datasets/AJMC/fr/HIPE-2022-v2.1-ajmc-test-fr.tsv --model Llama-2-70b-chat-hf -p ajmc_noguidelines_role
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model Mixtral-8x7B-Instruct-v0.1 -p hipe_guidelines_norole
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model Mixtral-8x7B-Instruct-v0.1 -p hipe_guidelines_role
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model Mixtral-8x7B-Instruct-v0.1 -p hipe_noguidelines_norole
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model Mixtral-8x7B-Instruct-v0.1 -p hipe_noguidelines_role
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model zephyr-7b-beta -p hipe_guidelines_norole
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model zephyr-7b-beta -p hipe_guidelines_role
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model zephyr-7b-beta -p hipe_noguidelines_norole
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model zephyr-7b-beta -p hipe_noguidelines_role
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model Meta-Llama-3-70B-Instruct -p hipe_guidelines_norole
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model Meta-Llama-3-70B-Instruct -p hipe_guidelines_role
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model Meta-Llama-3-70B-Instruct -p hipe_noguidelines_norole
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model Meta-Llama-3-70B-Instruct -p hipe_noguidelines_role
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model Llama-2-70b-chat-hf -p hipe_guidelines_norole
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model Llama-2-70b-chat-hf -p hipe_guidelines_role
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model Llama-2-70b-chat-hf -p hipe_noguidelines_norole
python extract_entities.py -i datasets/HIPE/de/HIPE-2022-v2.1-hipe2020-test-de.tsv --model Llama-2-70b-chat-hf -p hipe_noguidelines_role
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model Mixtral-8x7B-Instruct-v0.1 -p hipe_guidelines_norole
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model Mixtral-8x7B-Instruct-v0.1 -p hipe_guidelines_role
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model Mixtral-8x7B-Instruct-v0.1 -p hipe_noguidelines_norole
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model Mixtral-8x7B-Instruct-v0.1 -p hipe_noguidelines_role
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model zephyr-7b-beta -p hipe_guidelines_norole
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model zephyr-7b-beta -p hipe_guidelines_role
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model zephyr-7b-beta -p hipe_noguidelines_norole
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model zephyr-7b-beta -p hipe_noguidelines_role
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model Meta-Llama-3-70B-Instruct -p hipe_guidelines_norole
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model Meta-Llama-3-70B-Instruct -p hipe_guidelines_role
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model Meta-Llama-3-70B-Instruct -p hipe_noguidelines_norole
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model Meta-Llama-3-70B-Instruct -p hipe_noguidelines_role
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model Llama-2-70b-chat-hf -p hipe_guidelines_norole
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model Llama-2-70b-chat-hf -p hipe_guidelines_role
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model Llama-2-70b-chat-hf -p hipe_noguidelines_norole
python extract_entities.py -i datasets/HIPE/en/HIPE-2022-v2.1-hipe2020-test-en.tsv --model Llama-2-70b-chat-hf -p hipe_noguidelines_role
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model Mixtral-8x7B-Instruct-v0.1 -p hipe_guidelines_norole
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model Mixtral-8x7B-Instruct-v0.1 -p hipe_guidelines_role
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model Mixtral-8x7B-Instruct-v0.1 -p hipe_noguidelines_norole
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model Mixtral-8x7B-Instruct-v0.1 -p hipe_noguidelines_role
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model zephyr-7b-beta -p hipe_guidelines_norole
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model zephyr-7b-beta -p hipe_guidelines_role
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model zephyr-7b-beta -p hipe_noguidelines_norole
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model zephyr-7b-beta -p hipe_noguidelines_role
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model Meta-Llama-3-70B-Instruct -p hipe_guidelines_norole
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model Meta-Llama-3-70B-Instruct -p hipe_guidelines_role
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model Meta-Llama-3-70B-Instruct -p hipe_noguidelines_norole
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model Meta-Llama-3-70B-Instruct -p hipe_noguidelines_role
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model Llama-2-70b-chat-hf -p hipe_guidelines_norole
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model Llama-2-70b-chat-hf -p hipe_guidelines_role
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model Llama-2-70b-chat-hf -p hipe_noguidelines_norole
python extract_entities.py -i datasets/HIPE/fr/HIPE-2022-v2.1-hipe2020-test-fr.tsv --model Llama-2-70b-chat-hf -p hipe_noguidelines_role